/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
          "tertiary-dim": "#00cded",
          "on-primary-fixed": "#004821",
          "surface-container-highest": "#262626",
          "primary-dim": "#38ef84",
          "on-secondary": "#005e3e",
          "error-dim": "#d7383b",
          "inverse-primary": "#006e36",
          "on-secondary-container": "#e1ffeb",
          "inverse-on-surface": "#565554",
          "on-tertiary": "#005361",
          "surface-container-lowest": "#000000",
          "primary-fixed-dim": "#38ef84",
          "on-tertiary-fixed": "#00333d",
          "secondary-dim": "#64ecaf",
          "error": "#ff716c",
          "tertiary-container": "#00dcfe",
          "surface-bright": "#2c2c2c",
          "surface-container-high": "#201f1f",
          "on-secondary-fixed-variant": "#006946",
          "secondary-fixed": "#73fbbc",
          "background": "#0e0e0e",
          "tertiary-fixed-dim": "#00cded",
          "secondary-fixed-dim": "#64ecaf",
          "error-container": "#9f0519",
          "on-surface-variant": "#adaaaa",
          "surface-dim": "#0e0e0e",
          "on-tertiary-container": "#004956",
          "surface-container-low": "#131313",
          "inverse-surface": "#fcf8f8",
          "outline-variant": "#494847",
          "primary-container": "#29e67c",
          "surface-container": "#1a1919",
          "on-secondary-fixed": "#00492f",
          "on-primary-container": "#004d24",
          "tertiary-fixed": "#00dcfe",
          "on-primary": "#005d2d",
          "outline": "#777575",
          "on-background": "#ffffff",
          "on-error-container": "#ffa8a3",
          "surface-tint": "#4dfe90",
          "on-primary-fixed-variant": "#006833",
          "surface-variant": "#262626",
          "secondary": "#73fbbc",
          "surface": "#0e0e0e",
          "primary-fixed": "#4dfe90",
          "tertiary": "#7ce6ff",
          "on-error": "#490006",
          "on-surface": "#ffffff",
          "on-tertiary-fixed-variant": "#005361",
          "primary": "#4dfe90",
          "secondary-container": "#006c48"
      },
      fontFamily: {
          "headline": ["Space Grotesk"],
          "body": ["Manrope"],
          "label": ["Manrope"],
          "mono": ["JetBrains Mono"]
      }
    },
  },
  plugins: [],
}
